# Generated by Django 4.2.6 on 2024-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_gaps_location_alter_about_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gaps_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='gaps',
            name='fertilizer_application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaps',
            name='harvesting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaps',
            name='pest_and_disease_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaps',
            name='planting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaps',
            name='site_preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaps',
            name='yield_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaps',
            name='images',
            field=models.ManyToManyField(to='api.gapimage'),
        ),
    ]
