# Generated by Django 4.2.6 on 2024-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='GapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gaps_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('site_preparation', models.TextField(blank=True, null=True)),
                ('planting', models.TextField(blank=True, null=True)),
                ('fertilizer_application', models.TextField(blank=True, null=True)),
                ('pest_and_disease_control', models.TextField(blank=True, null=True)),
                ('harvesting', models.TextField(blank=True, null=True)),
                ('yield_information', models.TextField(blank=True, null=True)),
                ('images', models.ManyToManyField(to='api.gapimage')),
            ],
        ),
    ]
